language: ruby
cache:
  - bundler
before_install:
  - gem update bundler
matrix:
  include:
    - name: "1.9"
      rvm: 1.9.3
    - name: "2.0"
      rvm: 2.0.0
script:
  - RUBYOPT="$RUBYOPT $TEST_RUBYOPT" bundle exec rake
notifications:
  webhooks:
    - https://webhook.commit-email.info/
