language: ruby
cache:
  - bundler
before_install:
  - gem update bundler
matrix:
  include:
    - name: "1.9"
      rvm: 1.9.3
    - name: "2.0"
      rvm: 2.0.0
    - name: "2.1"
      rvm: 2.1
    - name: "2.2"
      rvm: 2.2
    - name: "2.3"
      rvm: 2.3
    - name: "2.4"
      rvm: 2.4
    - name: "2.4 + frozen string literal"
      rvm: 2.4
      env: TEST_RUBYOPT=--enable-frozen-string-literal
    - name: "2.5"
      rvm: 2.5
    - name: "2.5 + frozen string literal"
      rvm: 2.5
      env: TEST_RUBYOPT=--enable-frozen-string-literal
    - name: "2.6"
      rvm: 2.6
    - name: "2.6 + frozen string literal"
      rvm: 2.6
      env: TEST_RUBYOPT=--enable-frozen-string-literal
    - name: "2.7"
      rvm: 2.7
    - name: "2.7 + frozen string literal"
      rvm: 2.7
      env: TEST_RUBYOPT=--enable-frozen-string-literal
    - name: "master"
      rvm: ruby-head
    - name: "master + frozen string literal"
      rvm: ruby-head
      env: TEST_RUBYOPT=--enable-frozen-string-literal
    - name: "JRuby"
      rvm: jruby
  allow_failures:
    - name: "JRuby"
      rvm: jruby
  fast_finish: true
script:
  - RUBYOPT="$RUBYOPT $TEST_RUBYOPT" bundle exec rake
notifications:
  webhooks:
    - https://webhook.commit-email.info/
