name: Release
on:
  push:
    tags:
      - "*"
jobs:
  github:
    name: GitHub
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Extract release note
        run: |
          ruby \
            -e 'print("## test-unit "); \
                puts(ARGF.read.split(/^## /)[1]. \
                       gsub(/ {.+?}/, ""). \
                       gsub(/\[(.+?)\]\[.+?\]/) {$1})' \
            doc/text/news.md > release-note.md
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          body_path: release-note.md
          discussion_category_name: "Announcements"

